---
- name: copy the docker registry k8s yaml
  copy:
    src: "{{ item }}"
    dest: /tmp
    owner: "root"
    mode: 0744
  with_fileglob:
    - files/*

- name: copy the nginx-ingress nodePort service across
  template:
    src: ingress.yaml
    dest: /tmp/ingress.yaml
    mode: '0755'

- name: apply the docker registry deployment
  become: yes
  become_method: sudo
  shell: kubectl apply -f /tmp/deployment.yaml

- name: apply the docker registry service
  become: yes
  become_method: sudo
  shell: kubectl apply -f /tmp/service.yaml

- name: apply the docker registry ingress
  become: yes
  become_method: sudo
  shell: kubectl apply -f /tmp/ingress.yaml
