---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
    - role: common
      tags: common

- hosts: rpis
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
    - role: displays
      tags: displays

- hosts: masters
  roles:
    - role: k3s
      tags: k3s

- hosts: workers
  roles:
    - role: k3s
      tags: k3s

- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: "clear the deb cache and remove unused packages"
      apt:
        autoclean: yes
        autoremove: yes
