---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  tags: common
  roles:
    - role: common

- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  tags: displays
  roles:
    - role: displays
      when: enable_i2c_displays

- hosts: rpis
  tasks:
    - name: check if the container features have been enabled
      become: yes
      become_method: sudo
      replace:
        path: "{{ cmdline_config }}"
        regexp: '^(?!.*cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory)(.*?)(console=tty1 .+)$'
        replace: '\1cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory \2'
      register: enable_cgroups

    - name: "reboot and wait until ready"
      become: yes
      become_method: sudo
      reboot:
        msg: "Reboot initiated by ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
      when: enable_cgroups.changed

- hosts: controllers
  tags: k8s
  roles:
    - role: k0s # or k3s

- hosts: workers
  tags: k8s
  roles:
    - role: k0s # or k3s

- hosts: controllers
  tags: k8sextensions
  roles:
    - role: k8sextensions

- hosts: loadbalancers
  tags: loadbalancer
  become: yes
  become_method: sudo
  roles:
    - role: loadbalancer

- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: "clear the deb cache and remove unused packages"
      apt:
        autoclean: yes
        autoremove: yes
