---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
    - role: common
      tags: common

- hosts: rpis
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
    - role: displays
      tags: displays

- hosts: masters
  roles:
    - role: k0s # or k3s
      tags: k8s

- hosts: workers
  roles:
    - role: k0s # or k3s
      tags: k8s

#- hosts: masters
#  roles:
#    - role: k8sextensions
#      tags: k8sextensions

- hosts: loadbalancers
  become: yes
  become_method: sudo
  roles:
    - role: loadbalancer
      tags: loadbalancer

- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: "clear the deb cache and remove unused packages"
      apt:
        autoclean: yes
        autoremove: yes
