---
- include: prerequisites.yml
  become: yes
  become_method: sudo

- include: controllers.yml
  when: inventory_hostname in groups['controllers']

- include: workers.yml
  when: inventory_hostname in groups['workers']
