---
- name: enable the necessary modules required for k0s
  blockinfile:
    path: /etc/modules
    block: |
      modprobe overlay
      modprobe nf_conntrack
      modprobe br_netfilter
  register: enable_modules

- name: "reboot and wait until ready"
  reboot:
    msg: "Reboot initiated by ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: enable_modules.changed

- name: download k0s version '{{ k0s_version }}'
  get_url:
    url: https://github.com/k0sproject/k0s/releases/download/{{ k0s_version }}/k0s-{{ k0s_version }}-{{ arch }}
    dest: /usr/bin/k0s
    mode: '0755'

- name: copy the k0s crictl config
  copy:
    src: "{{ item }}"
    dest: /etc/
    owner: "root"
    mode: 0644
  with_fileglob:
    - files/*
