---
- name: check if the container features have been enabled
  become: yes
  become_method: sudo
  replace:
    path: "{{ cmdline_config }}"
    regexp: '^(?!.*cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory)(.*?)(console=tty1 .+)$'
    replace: '\1cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory \2'
  register: enable_cgroups

- name: enable the necessary modules required for k0s
  become: yes
  become_method: sudo
  blockinfile:
    path: /etc/modules
    block: |
      modprobe overlay
      modprobe nf_conntrack
      modprobe br_netfilter
  register: enable_modules

- name: "reboot and wait until ready"
  become: yes
  become_method: sudo
  reboot:
    msg: "Reboot initiated by ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: enable_cgroups.changed or enable_modules.changed

- name: download k0s version '{{ k0s_version }}'
  become: yes
  become_method: sudo
  get_url:
    url: https://github.com/k0sproject/k0s/releases/download/{{ k0s_version }}/k0s-{{ k0s_version }}-arm64
    dest: /usr/bin/k0s
    mode: '0755'
