---
- name: enable the necessary modules required for k0s
  blockinfile:
    path: /etc/modules
    block: |
      modprobe overlay
      modprobe nf_conntrack
      modprobe br_netfilter
  register: enable_modules

- name: "reboot and wait until ready"
  reboot:
    msg: "Reboot initiated by ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: enable_modules.changed

- name: download k0s version '{{ k0s_version }}'
  get_url:
    url: https://github.com/k0sproject/k0s/releases/download/{{ k0s_version }}/k0s-{{ k0s_version }}-{{ arch }}
    dest: /usr/bin/k0s
    mode: '0755'

- name: copy the k0s crictl config
  copy:
    src: "{{ item }}"
    dest: /etc/
    owner: "root"
    mode: 0644
  with_fileglob:
    - files/*

- name: "kubectl: check if it is already installed"
  stat:
    path: /usr/local/bin/kubectl
  register: stat_result

- name: "kubectl: install"
  when: not stat_result.stat.exists
  block:
    - name: "kubectl: get the latest stable version"
      uri:
        url: https://dl.k8s.io/release/stable.txt
        return_content: yes
      register: kubectl_version

    - name: "kubectl: download the file"
      get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version.content }}/bin/linux/{{ arch }}/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'

- pip:
    name:
      - openshift
      - kubernetes
      - kubernetes-validate

- name: install "helm" with option --classic
  community.general.snap:
    name: helm
    classic: yes

- name: "crictl: check if it is already installed"
  stat:
    path: /usr/local/bin/crictl
  register: crictl_stat_result

- name: "crictl: install"
  when: not crictl_stat_result.stat.exists
  block:
    - name: "crictl: download crictl version '{{ crictl_version }}'"
      get_url:
        url: https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ crictl_version }}/crictl-{{ crictl_version }}-linux-{{ arch }}.tar.gz
        dest: /tmp/crictl-{{ crictl_version }}-linux-{{ arch }}.tar.gz
        mode: '0755'

    - name: "crictl: Extract the tarball"
      unarchive:
        src: /tmp/crictl-{{ crictl_version }}-linux-{{ arch }}.tar.gz
        dest: /usr/local/bin
        remote_src: yes

    - name: "crictl: delete tarball"
      file:
        state: absent
        path: /tmp/crictl-{{ crictl_version }}-linux-{{ arch }}.tar.gz