---
- name: populate service facts
  service_facts:

- name: install k0s service on workers
  become: yes
  become_method: sudo
  when: 'ansible_facts.services["k0sworker.service"] is not defined'
  block:

    - name: install k0s worker node as a service
      shell: k0s install worker --token-file /var/lib/k0s/join-token

    - name: enable the service
      systemd:
        name: k0sworker
        enabled: True

    - name: force systemd to reread configs (2.4 and above)
      systemd:
        daemon_reload: yes

    - name: start k0s worker
      systemd:
        state: started
        name: k0sworker

- name: install k0s service on workers
  shell: "kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/worker=worker"
  delegate_to: "{{ item }}"
  loop: "{{ groups['controllers'] }}"

- name: (openebs storage) enable the iSCSI
  systemd:
    name: iscsid
    enabled: yes
    force: yes
  when: openebs
