grafana:
  enabled: true
  initChownData:
    enabled: false
  persistence:
    type: pvc
    enabled: true
    accessModes:
      - ReadWriteMany
    size: 2Gi
    subPath: k8s/grafana/data
    existingClaim: prometheus-nfs

prometheus:
  enabled: true
  alertmanager:
    enabled: false
  server:
    persistentVolume:
      enabled: true
      accessModes:
        - ReadWriteOnce
      mountPath: /data
      subPath: k8s/prometheus/data
      existingClaim: "prometheus-nfs"
  nodeExporter:
    tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
