---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: registry
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  tls:
    - secretName: registry
      hosts:
        - {{ registry_domain }}
  rules:
    - host: {{ registry_domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: registry
              servicePort: 5000
