---
- name: check whether the i2c libraries have been installed
  shell: ls /usr/local/lib/python3.7/dist-packages/ | grep SSD1306
  ignore_errors: yes
  no_log: True
  register: i2c_lib_check

- name: ensure i2c python libraries is installed
  apt:
    name: ['python3-dev', 'python3-smbus', 'i2c-tools', 'python3-pil', 'python3-pip', 'python3-setuptools', 'python3-rpi.gpio']
    update_cache: yes
    state: latest
  when: i2c_lib_check.failed

- name: "check if {{ firmware_config }} file exists"
  stat:
    path: "{{ firmware_config }}"
  register: config_file
  when: i2c_lib_check.failed

- name: enable the i2c interface during boot
  lineinfile:
    path: "{{ firmware_config }}"
    line: dtparam=i2c_arm=on
    state: present
  when: i2c_lib_check.failed and config_file.stat.exists

- name: enable the i2c modules during boot
  lineinfile:
    path: /etc/modules
    line: i2c-dev
    state: present
  when: i2c_lib_check.failed

- name: Reboot host and wait for it to restart
  reboot:
    msg: "Reboot initiated by ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: i2c_lib_check.failed

- name: use i2cdetect command to use the module on the i2c bus
  shell: i2cdetect -y 1
  when: i2c_lib_check.failed

- name: clone the python repo to use SSD1306-based OLED displays
  git:
    repo: https://github.com/adafruit/Adafruit_Python_SSD1306.git
    dest: /tmp/adafruit_ssd1306
  when: i2c_lib_check.failed

- name: install the python i2c libraries
  command: chdir=/tmp/adafruit_ssd1306 python3 setup.py install
  when: i2c_lib_check.failed

- name: remove the directory
  file:
    state: absent
    path: "/tmp/adafruit_ssd1306"
  when: i2c_lib_check.failed

- name: copy the latest i2c display scripts
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    owner: "root"
    mode: 0744
  with_fileglob:
    - files/*
