# Configures the cluster to use nginx ingress controller
# https://kubernetes.github.io/ingress-nginx/
---
- name: download mandatory nginx-ingress yaml
  get_url:
    url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml
    dest: /tmp/nginx-mandatory.yaml
    mode: '0755'

- name: copy the nginx-ingress nodePort service across
  template:
    src: service.yaml
    dest: /tmp/nginx-nodeport-service.yaml
    mode: '0755'

- name: swap the default controller image with the arm image
  lineinfile:
    path: /tmp/nginx-mandatory.yaml
    regexp: '^(.*image:).*$'
    line: '\1 quay.io/kubernetes-ingress-controller/nginx-ingress-controller-arm:{{ nginx_ingress_controller_version }}'
    state: present
    backrefs: yes

- name: apply nginx-ingress mandatory definition yaml
  become: yes
  become_method: sudo
  shell: kubectl apply -f /tmp/nginx-mandatory.yaml

- name: apply nginx-ingress node port service definition yaml
  become: yes
  become_method: sudo
  shell: kubectl apply -f /tmp/nginx-nodeport-service.yaml
