---
- name: add current server to hosts files
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost.*'
    line: '127.0.0.1 localhost {{ inventory_hostname }}'
    state: present

- name: add all workers to controllers hosts files
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ hostvars[item].ansible_host }}.*$"
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    state: present
  when: inventory_hostname in groups['controllers'] and hostvars[item].ansible_host is defined
  with_items: "{{ groups.workers }}"

- name: add controllers to workers hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ hostvars[item].ansible_host }}.*$"
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    state: present
  when: inventory_hostname in groups['workers'] and hostvars[item].ansible_host is defined
  with_items: "{{ groups.controllers }}"

