---
- name: add the user '{{ ansible_user_id }}' to the system
  user:
    name: "{{ ansible_user_id }}"

- name: add '{{ ansible_user_id }}' to the list of sudoers
  copy:
    dest: "/etc/sudoers.d/020_{{ ansible_user_id }}"
    content: |
      {{ ansible_user_id }} ALL=(ALL:ALL) ALL

- name: copy across your ssh key
  authorized_key:
    user: "{{ ansible_user_id }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: disable password authentication
  replace:
    path: /etc/ssh/sshd_config
    regexp: '#PasswordAuthentication yes'
    replace: 'PasswordAuthentication no'
  notify: restart ssh

- block:
    - name: check if the container features have been enabled
      shell: "cat /boot/cmdline.txt | grep cgroup_enable"
  rescue:
    - name: enable container features
      replace:
        path: /boot/cmdline.txt
        regexp: '^(.*)$'
        replace: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'

- name: remove the default 'pi' user
  user:
    name: pi
    state: absent
    remove: yes

- hostname:
    name: "{{ inventory_hostname }}"

- name: ensure a locale exists
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: update the apt cache
  apt:
    force_apt_get: true
    update_cache: yes
    cache_valid_time: 3600

- name: update all packages to the latest version
  apt:
    upgrade: dist

- name: install python-apt to enable ansible check
  apt:
    name: python-apt
    state: latest
