---
- name: include the secret variables
  include_vars: .secret
# Creates the new user and sets up the ssh config
- include: user_ssh.yml
# sets the hostname of the machine
- hostname:
    name: "{{ inventory_hostname }}"
# Updates the apt cache and installs minimum required software after installing updates
- include: packages.yml
# setup tailscale to enable wireguard connectivity between the loadbalancer and nodes
- include: tailscale.yml
# Sets up the /etc/hosts file
- include: hostfile.yml
# Disables bluetooth and wifi
- include: disable_wifi_radio.yml
  when: disable_wifi
