# https://fluxcd.io/docs/get-started/

- name: include the secret variables
  include_vars: .secret

- name: "[fluxcd] get the fluxcd cli tool"
  get_url:
    url: https://fluxcd.io/install.sh
    dest: "{{ extensions_dir }}/fluxcd/install.sh"
    mode: '0664'

- name: "[fluxcd] install fluxcd controller"
  shell: "{{ extensions_dir }}/fluxcd/install.sh"
  environment:
    GITHUB_USER: "{{ git_username }}"
    GITHUB_TOKEN: "{{ git_token }}"
