---
######################################################################
# Kube Prometheus setup instructions:
#   https://github.com/prometheus-operator/kube-prometheus#installing
######################################################################

- name: (grafana local) set the extension directory for grafana cloud
  set_fact:
    grafana_local_ext_dir: "{{ extensions_dir }}/observability/grafana-local"
    grafana_local_namespace: observability
    grafana_local_manifests:
      - 'prometheus.yaml'
      - 'promtail.yaml'

- name: (grafana local) ensure the extensions directory exists
  file:
    path: "{{ grafana_local_ext_dir }}"
    state: directory

- name: (grafana local) include the secret variables
  include_vars: .secret

- name: (grafana cloud) copy across the agent config map
  template:
    src: "{{ item }}.j2"
    dest: "{{ grafana_local_ext_dir }}/{{ item }}"
  loop: "{{ grafana_local_manifests }}"

- name: (grafana local) create the '{{ grafana_local_namespace }}' namespace
  k8s:
    name: {{ grafana_local_namespace }}
    api_version: v1
    kind: Namespace
    state: present

- name: (grafana local) deploy the prometheus manifests
  k8s:
    state: present
    src: "{{ grafana_local_ext_dir }}/prometheus.yaml"
    validate:
      fail_on_error: yes

- name: (grafana local) deploy the promtail daemonset
  k8s:
    state: present
    src: "{{ grafana_local_ext_dir }}/promtail.yaml"
    validate:
      fail_on_error: yes

- name: (grafana local) install 'grafana/tempo' helm chart
  community.kubernetes.helm:
    chart_ref: tempo
    chart_repo_url: "https://grafana.github.io/helm-charts"
    chart_version: "{{ tempo_helm_version }}"
    release_name: tempo
    release_namespace: {{ grafana_local_namespace }}

- name: (grafana local) install 'grafana/grafana' helm chart
  community.kubernetes.helm:
    chart_ref: grafana
    chart_repo_url: "https://grafana.github.io/helm-charts"
    chart_version: "{{ grafana_helm_version }}"
    release_name: grafana
    release_namespace: {{ grafana_local_namespace }}
