---
- name: ensure the extensions directory exists
  file:
    path: "{{ extensions_dir }}"
    state: directory

- include: metallb.yml

- include: traefik-ingress.yml

- include: longhorn-storage.yml

#- include: kube-prometheus-obs.yml

- include: grafana-cloud-obs.yml

- include: cert-manager.yml

#- include: fluxcd.yaml
