---
- name: ensure the extensions directory exists
  file:
    path: "{{ extensions_dir }}"
    state: directory

## Loadbalancing
- include: metallb.yml

## Ingress
- include: traefik-ingress.yml

## Storage
# - include: longhorn.yml
- include: nfs-persistent-volume.yml

## Observability
# - include: kube-prometheus.yml
# - include: grafana-cloud.yml
- include: grafana-in-cluster.yml

## Certificate management
- include: cert-manager.yml

## Gitops
#- include: fluxcd.yaml
