---
- name: ensure the extensions directory exists
  file:
    path: "{{ extensions_dir }}"
    state: directory

- include: loadbalancer.yml

- include: ingress.yml

- include: storage.yml

#- include: observability.yml

- include: cert-manager.yml
