---
- name: ensure the extensions directory exists
  file:
    path: "{{ extensions_dir }}"
    state: directory

## Loadbalancing
- include: metallb.yml
  when: not ingress_node_port

## Ingress
- include: traefik-ingress.yml

## Storage
- include: longhorn.yml
  when: longhorn

## Observability
- include: kube-prometheus.yml
  when: kube_prom
- include: grafana-cloud.yml
  when: grafana_cloud
- include: grafana-in-cluster.yml
  when: grafana_in_cluster

## Certificate management
- include: cert-manager.yml
  when: cert_manager

## Gitops
- include: fluxcd.yaml
  when: fluxcd
