###
# https://github.com/kubernetes/examples/tree/master/staging/volumes/nfs
###
---
- name: (nfs pv) include the secret variables
  include_vars: .secret

- name: (nfs pv) create an NFS persistent volume
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: nfs
      spec:
        capacity:
          storage: "{{ nfs_pv_size }}"
        accessModes:
          - ReadWriteMany
        nfs:
          server: "{{ nfs_pv_server }}"
          path: "{{ nfs_pv_path }}"
