---
# --------
# Setup instructions:
#   https://github.com/prometheus-operator/kube-prometheus#installing
# --------
- name: "[observability] checkout kube-prometheus"
  git:
    repo: 'https://github.com/prometheus-operator/kube-prometheus.git'
    dest: "{{ extensions_dir }}/kube-prometheus"
    version: "{{ prometheus_operator_version }}"
    force: yes

- name: "[observability] deploy kube-prometheus"
  shell: kubectl apply -f "{{ extensions_dir }}/kube-prometheus/manifests/setup"

- name: "[observability] wait for kubeconfig to be created"
  shell: until kubectl get servicemonitors --all-namespaces ; do date; sleep 1; echo ""; done

# https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/prometheus-prometheus.yaml
- name: "[observability] add pvc to the prometheus statefulset"
  blockinfile:
    path: "{{ extensions_dir }}/kube-prometheus/manifests/prometheus-prometheus.yaml"
    insertafter: EOF
    block: |2 # 2 is for indenting
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              resources:
                requests:
                  storage: 2Gi

- name: "[observability] install kube-prometheus to monitor the cluster"
  shell: kubectl apply -f "{{ extensions_dir }}/kube-prometheus/manifests/"

- name: "[observability] ensure the extensions directory exists"
  file:
    path: "{{ extensions_dir }}/kube-prometheus/manifests/ingress"
    state: directory

- name: "[observability] copy the files to '{{ extensions_dir }}/kube-prometheus/manifests/ingress'"
  copy:
    src: "{{ item }}"
    dest: "{{ extensions_dir }}/kube-prometheus/manifests/ingress/"
  with_fileglob:
    - files/*

- name: "[observability] deploy the kube-prometheus ingress"
  k8s:
    state: present
    namespace: monitoring
    src: "{{ extensions_dir }}/kube-prometheus/manifests/ingress/kube-prometheus-ingress.yaml"
    validate:
      fail_on_error: yes

#TODO: Add the Grafana dashboard for the cluster