---
# ----
# Setup instructions:
#   https://longhorn.io/docs/1.1.1/deploy/install/install-with-kubectl/
# ----
- name: "[storage] ensure the extensions directory exists"
  file:
    path: "{{ extensions_dir }}/storage"
    state: directory

- name: "[storage] download the longhorn operator yam"
  get_url:
    url: https://raw.githubusercontent.com/longhorn/longhorn/{{ longhorn_version }}/deploy/longhorn.yaml
    dest: "{{ extensions_dir }}/storage/longhorn.yaml"
    mode: '0664'

- name: "[storage] install the longhorn operator"
  k8s:
    state: present
    src: "{{ extensions_dir }}/storage/longhorn.yaml"
