---
# https://longhorn.io/docs/1.1.1/deploy/install/install-with-kubectl/
- name: install the longhorn operator
  shell: kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/{{ longhorn_version }}/deploy/longhorn.yaml
