---
#######################################################################################
# Traefik Ingress instructions:
#   https://doc.traefik.io/traefik/getting-started/install-traefik/#use-the-helm-chart
#   https://traefik.io/blog/from-zero-to-hero-getting-started-with-k0s-and-traefik/
#######################################################################################

- name: (traefik ingress) set the facts
  set_fact:
    traefik_namespace: ingress

- name: (traefik ingress) create the '{{ traefik_namespace }}' namespace for traefik
  k8s:
    name: "{{ traefik_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: (traefik ingress) install 'traefik' helm chart
  community.kubernetes.helm:
    chart_ref: traefik
    chart_repo_url: "https://helm.traefik.io/traefik"
    chart_version: "{{ traefik_helm_version }}"
    release_name: traefik
    release_namespace: "{{ traefik_namespace }}"
    values: "{{ lookup('template', 'helm-values-traefik.yaml.j2') | from_yaml }}"

- name: (traefik ingress) try 5 times (with 5 seconds intervals) to get ingress loadbalancer IP
  shell: kubectl get svc -n "{{ traefik_namespace }}" traefik -o=jsonpath='{.status.loadBalancer.ingress[0].ip}'
  register: ingress_ip

- name: (traefik ingress) set the ingress ip fact for loadbalancers
  set_fact:
    ingress_ip: "{{ ingress_ip.stdout }}"
  run_once: true
  delegate_facts: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['loadbalancers'] }}"
